# Generated by Django 3.1.5 on 2021-02-09 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=10)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('display_name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('display_name', models.CharField(max_length=10)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('display_name', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('placement', models.IntegerField()),
                ('placement_pts', models.IntegerField(blank=True, default=0)),
                ('gross_placement_pts', models.IntegerField(blank=True, default=0)),
                ('kill_pts', models.IntegerField()),
                ('gross_kill_pts', models.IntegerField(blank=True, default=0)),
                ('total_pts', models.IntegerField(blank=True, default=0)),
                ('gross_total_pts', models.IntegerField(blank=True, default=0)),
                ('chicken_dinner', models.IntegerField(blank=True, default=0)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.squad')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'match_number', 'squad', 'author')},
            },
        ),
        migrations.CreateModel(
            name='PointsTableInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('bottom_left_text', models.CharField(blank=True, max_length=25, null=True)),
                ('bottom_center_text', models.CharField(blank=True, max_length=25, null=True)),
                ('bottom_right_text', models.CharField(blank=True, max_length=25, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_pt_set', to='Site.image')),
                ('bottom_center_images', models.ManyToManyField(blank=True, related_name='btm_cn_set', to='Site.Image')),
                ('bottom_left_images', models.ManyToManyField(blank=True, related_name='btm_lt_set', to='Site.Image')),
                ('bottom_right_images', models.ManyToManyField(blank=True, related_name='btm_rt_set', to='Site.Image')),
                ('top_left_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_left_pt_set', to='Site.image')),
                ('top_right_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_right_pt_set', to='Site.image')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'match_number', 'author')},
            },
        ),
        migrations.CreateModel(
            name='PlacementPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('placement', models.IntegerField()),
                ('point', models.IntegerField()),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Site.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'match_number', 'placement', 'author')},
            },
        ),
    ]
